# Site Info
title: Hyeyoon Cho
tagline: 'Cho's github blog'
description: 'Blog to leave what I've learnt and interested'
baseurl: "/"
url: http://hyeyoon0808.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Hyeyoon Cho
  description: Passionate to experience many fields.
  gravatar:  # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/hyeyooncho
    github:    https://github.com/hyeyoon0808
    email:     https://mail.google.com/mail/u/0/?view=cm&fs=1&tf=1&source=mailto&to=hyeyooncho08@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/'
    # - { Categories: '/blog/categories/' }

    # - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/hyeyoon0808'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/aurora.jpg

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'Hyeyoon' # leave blank if you don't want disqus

